### ISSUE TITLE
Does replace existing agent keep existing user capabilties?

### ISSUE THREAD

**Issue by japj** [Microsoft/VSTSAgent.PowerShell#9]
Install-VSTSAgent has an option to replace an existing agent.
Will existing user capabilities be kept when ‘upgrading’ an agent or will user capabilities need to be manually set again after uninstall/re-install of the agent?

**Comment by jwittner** [comment]
The capabilities will be based on the new agent. Using the replace flag will force any currently registered agents with the same name to be replaced in the pool, instead of reporting an error. This is different than an 'upgrade' scenario I think. If you're looking for a simple path to update the VSTS agent versions you have you can force that by right clicking the pool in your browser and selecting 'Update all agents'. 

See here for more docs: https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/agents?view=vsts#agent-version-and-upgrades
